### ISSUE TITLE
ul.line-legend CSS style missing whilst using metric_history

### ISSUE THREAD

**Issue by mvillarejo** [bradmontgomery/django-redis-metrics#30]
Hello,

I successfully upgraded to 0.8.0 my project, things are looking good. Thanks a lot for your work.

One bit that seems to be not working is that ```ul.line-lgend``` style class is defined here: ```redis_metrics/templates/redis_metrics/base.html``` and therefore it's not imported when using templatetags, I've tried with metric_history and it does not get the style and althrough if I create the graph on ```/metrics``` it does work without problems.

thanks

**Comment by bradmontgomery** [comment]
I've *finally* taken some time to look at this, and I'm marking as wontfix for the following reasons:

1. If you're using the built-in templates, it shouldn't be an issue, because you'll get the css rules that you mentioned.
2. If you're using the stand-alone tag with your own templates, it's likely that you've already styled your own site to your liking.
3. If you've done 2 above, I don't want to force any CSS on you that would break your customization.

Taking those three things into consideration, I'm not sure how else I would approach this problem.  I'm always open to other ideas, though, so feel free to let me know if you've got any thoughts on this.
